name: better_enum
description: Package that provides a better way (java-like) to write enums
version: 1.0.0
homepage: https://github.com/Mai-Lapyst/dart_better_enum
repository: https://github.com/Mai-Lapyst/dart_better_enum

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec